[project]
name = "strawberry-django-firebase-auth"
version = '1.4.0'
authors = [{ name = 'Ole Odendahl', email = 'oleodendahl@gmail.com' }]
description = "Authentication provider for strawberry-django and Google Firebase's Authentication service."
license = { text = 'License :: OSI Approved :: MIT License' }
keywords = ['strawberry', 'django', 'firebase', 'auth', 'jwt', 'graphql']
readme = 'README.md'
requires-python = ">=3.11"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 5.2',
    'Framework :: Django :: 6.0',
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'License :: OSI Approved :: MIT License',
]
dependencies = ['django >= 5.2', 'django-environ', 'firebase-admin', 'strawberry-graphql']

[project.urls]
repository = 'https://github.com/oleo65/strawberry-django-firebase-auth'

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
[tool.pylint]
[tool.pylint.master]
disable = [
    'C0114',
    'C0115',
    'missing-function-docstring',
    'no-else-return',
    'too-few-public-methods',
    'too-many-ancestors',
    'too-many-instance-attributes',
    'too-many-arguments',
    'too-many-return-statements',
]

[tool.pylint.format]
max-line-length = 140

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "pylint-django>=2.7.0",
    "pytest>=9.0.3",
]
